version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      SFTP_SERVER_HOSTNAME: ${SFTP_SERVER_HOSTNAME}
      SFTP_SERVER_USERNAME: ${SFTP_SERVER_USERNAME}
      SFTP_SERVER_PASSWORD: ${SFTP_SERVER_PASSWORD}
      SFTP_SERVER_DIRECTORY: ${SFTP_SERVER_DIRECTORY}
      SFTP_SERVER_1_PORT: ${SFTP_SERVER_1_PORT}
      SFTP_SERVER_2_PORT: ${SFTP_SERVER_2_PORT}
      SFTP_SERVER_3_PORT: ${SFTP_SERVER_3_PORT}


  vue:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:8080"
    volumes:
      - ./vue-app:/app
    environment:
      NODE_ENV: development
